### ISSUE TITLE
Feature: User can see the importance of buying quality makeup products

### ISSUE THREAD

**Issue by susieggrim** [Susana-Gutierrez/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the importance of buying quality makeup products

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to open the application showing a text explaining the importance of buying natural makeup products. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 1-Desktop](https://user-images.githubusercontent.com/82625148/137432350-1e0bc86f-8e35-4c9d-a2d3-b5bc6a84c51a.JPG)

![Feature 1-Mobile](https://user-images.githubusercontent.com/82625148/137432363-51aec52c-c9e1-403a-a819-b69158ae4bc2.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set the page background colors.
- [x] Add title of the application.
- [x] Add text
- [x] Add picture
- [x] Add search product button
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
