### ISSUE TITLE
Feature: User can view products by type

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view products by type: blush, eyebrow, eyeliner, eyeshadow, foundation, lip liner, lipstick, and mascara.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User should be able search products by type. Clicking the "Search Product" button, a modal will be displayed to select the product and search. After searching, user should see a list of the products with picture, brand, name, and price. User should be able to go back to the first screen clicking the back button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature2-Desktop](https://user-images.githubusercontent.com/82625148/137441176-8e99bbe7-ec04-4e70-9bc6-0bbb618e2692.JPG)

![Feature2-Mobile](https://user-images.githubusercontent.com/82625148/137441189-6ab93d29-f20c-4fdb-a571-f2f6c0137690.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal with a dropdown list  showing a list of product types: blush, eyebrow, eyeliner, eyeshadow, foundation, lip liner, lipstick and mascara.
- [x] Make sure the modal is showed after clicking the "Search Product" button.
- [x] Ensure that a  list of products with picture, brand, name and price is showed after clicking the modal "Search" button. 
- [x] Make sure the list is empty if "Product Type" wasn't selected.
- [x] Make sure first page is displayed after "Back" button is clicked.   
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
