### ISSUE TITLE
Feature: User can search products by type and tags.

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search products by type and tags: vegan, gluten free, natural, organic, hypoallergenic, no talc. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User should be able to add tags such as vegan, gluten free, natural, organic, hypoallergenic, no talc to the product search.  These tags will be selected using check boxes. If  tags are selected, the list will display products with these tags only. If tags are not selected, the list will show all products matching the the product type value shown in the dropdown list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature3-Desktop](https://user-images.githubusercontent.com/82625148/137443448-55ea52b1-8df4-4236-8ee9-6fdacf63a558.JPG)

![Feature3-Mobile](https://user-images.githubusercontent.com/82625148/137443459-d7bb10d1-7efd-4921-b702-59b3503addc4.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Update modal adding check boxes with tags values: Vegan, Gluten Free, Hypoallergenic, Organic, No talc, Natural.
- [ ] Make sure the list displays products with selected tags only.
- [ ] Make sure all the products matching the product type value of the dropdown box are shown if tags are not selected.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
