### ISSUE TITLE
Feature: User can view products details

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view products details

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User should be able to click on the products picture to see details such as name, brand, price, shades, description and tags. User will be redirected to previous list after clicking the back button. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature4-Desktop](https://user-images.githubusercontent.com/82625148/137446359-0f65061e-9aeb-437f-87eb-bb80fa28057d.JPG)

![Feature4-Mobile](https://user-images.githubusercontent.com/82625148/137446386-a90a1f46-07bf-4a7e-9ffe-633645a5a987.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make sure user can see details of the product after clicking the picture. 
- [ ] Make sure shades are added in small circles. 
- [ ] Ensure user can see the previous list after clicking the Back button
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
