### ISSUE TITLE
Feature: User can be redirected to the product's website and buy it.

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can be redirected to the product website and buy it.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to visit the product's website to buy it. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature5-Desktop](https://user-images.githubusercontent.com/82625148/137447116-31d4b6e5-0ea8-4f63-ab11-a4dbfb8a2fdf.JPG)

![Feature5-Mobile](https://user-images.githubusercontent.com/82625148/137447124-341cf322-aba1-4c02-86e2-e582f2feb454.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add new "Buy Now" button. 
- [ ] Make sure the user is redirected to the product's website after click in the "Buy Now" button.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
